<?php

return array (
  'name' => '飞燕文具店',
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'reg_integral' => '10',
  'sign_integral' => '10',
  'merchant_name' => '彦语',
  'merchant_logo' => '/uploads/favicon.ico',
  'merchant_address' => '江西省南昌市青山湖区上海路住宅区',
  'buy_send_integral' => 
  array (
    '消费金额' => '1',
    '积分金额' => '1',
  ),
  'tel' => '13687074488',
  'gold_medal_service' => '24小时贴心管家服务，让您买的放心',
  'lightning_distribution' => '极速发货，专业快递配送',
  'guarantee_authenticity' => '无',
  'admin_avatar' => '/uploads/20200608/721365a01f2a42d7cdb3702a1e42fb9e.png',
  'commission_rate' => '0.06',
  'share' => '15',
  'un_order_time' => '5',
  'confirm_order_time' => '7',
  'second_commission_rate' => '0.03',
  'dealer_switch' => '1}}}}',
  'good_order' => '7',
  'automatic_evaluation' => '3',
  'is_use_coupon' => '1',
  'is_open_sign' => '1',
  'sign_cycle' => '0',
  'sing_reward_default_first' => '5',
  'sign_reward_default_day' => '10',
  'sign_old' => '1',
  'sign_old_price' => '10',
  'sign_old_type' => '1',
  'sign_rule' => '<p><b><br />积分获取方式</b></p><p>购买商品消费后可以获取积分<br /><br /><b>积分用途</b><br />积分在用户下单时可以抵扣消费</p>',
  'is_open_special_sign' => '1',
  'special_sign_limit_date' => '',
  'special_sign_reward_type' => 'coupon',
  'special_sign_reward_data' => '',
  'logo' => '/uploads/20210304/454acdc368f0d2c14550815dce02b15a.jpg',
  'title' => '飞燕文具店',
  'vip1_frequency' => '6',
  'vip1_interval' => '60',
  'vip2_frequency' => '12',
  'vip2_interval' => '30',
  'kf_phone' => '13970805531',
  'is_to_pay' => '1',
  'distribution_rate' => '0.03',
  'register_member_score' => '100',
  'score_ratio' => '1',
  'distribution_score_ratio' => '0.10',
  'distribution_apply_money' => '390',
  'share_poster' => '/uploads/20200612/12f368d464e45cc3b786741e532dda6c.jpg',
  'spike_distribution_rate' => '0.001',
  'group_distribution_rate' => '0.001',
  'ordinary_commission' => '5',
  'package_freight' => '0',
  'package_freight_text' => '',
  'min_money' => '50',
  'wx_min_money' => '20',
  'automatic_re_and_eva' => '7',
  'refund_review_time' => '7',
  'share_background_picture' => '/uploads/20200612/12f368d464e45cc3b786741e532dda6c.jpg',
  'two_distribution_rate' => '0.01',
  'two_spike_distribution_rate' => '0.001',
  'two_group_distribution_rate' => '0.001',
  'is_shopingcart' => '1',
  'image_thumb' => '1',
  'freight' => 
  array (
    100 => '6',
  ),
  'product_points' => '20',
  'VIP_introduction' => '购物满1000元，自动升级为vip会员，升级后享受vip价格',
  'Noticeto_users' => '资料正在整理中...',
  '测试12' => '',
  123 => '1',
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'sign_basic' => '签到设置',
  ),
);