<?php

namespace app\admin\controller\report;

use app\common\controller\Backend;
use app\common\model\Litestoreorder;
use fast\Date;

class Money extends Backend
{
    protected $noNeedLogin = ['getData'];

    /** @var Litestoreorder */
    public $model = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('Litestoreorder');
    }

    public function index()
    {
        $this->assign('cuDate', date('Y-m-d'));
        return $this->fetch();
    }

    public function getData()
    {
        $mode = $this->request->param('mode');
        $row = $this->request->param('row', 7);
        $startTime = strtotime($this->request->param('start', 0));
        $endTime = strtotime($this->request->param('end', 0));
        $endTime && $endTime += Date::DAY - 1;

        switch ($mode) {
            case 'month'://月视图
                $formatter = '%Y-%m';
                $timeUnit = Date::MONTH;
                $timeFormatter = 'Y-m';
                break;
            case 'year'://年视图
                $formatter = '%Y';
                $timeUnit = Date::YEAR;
                $timeFormatter = 'Y';
                break;
            case 'day'://日视图
            default:
                $formatter = '%Y-%m-%d';
                $timeUnit = Date::DAY;
                $timeFormatter = 'Y-m-d';
                break;
        }

        $field = "FROM_UNIXTIME(createtime,'$formatter') as time,sum(pay_price) as money";
        $row != 0 && $this->model->page(1, $row);
        $startTime && $endTime && $this->model->where(['createtime' => ['between', [$startTime, $endTime]]]);
        $moneyList = $this->model->field($field)->order('time', 'desc')->group('time')->select();

        $payMoney = model('admin/Litestoreorderrefund');
        $field = "FROM_UNIXTIME(create_time,'$formatter') as time,sum(refund_money) as refund_money";
        $row != 0 && $payMoney->page(1, $row);
        $startTime && $endTime && $payMoney->where(['create_time' => ['between', [$startTime, $endTime]]]);
        $refundList = $payMoney->where(['order_id' => ['neq', 'null'], 'apply_status' => 2])->field($field)->order('time', 'desc')->group('time')->select();

        $withdraw = model('admin/Withdraw');
        $field = "FROM_UNIXTIME(create_time,'$formatter') as time,sum(money) as withdraw_money";
        $row != 0 && $withdraw->page(1, $row);
        $startTime && $endTime && $withdraw->where(['create_time' => ['between', [$startTime, $endTime]]]);
        $withdrawList = $withdraw->where(['status' => ['not in', '1,3']])->field($field)->order('time', 'desc')->group('time')->select();

        $moneyList = collection($moneyList)->toArray();
        $withdrawList = collection($withdrawList)->toArray();
        $refundList = collection($refundList)->toArray();

        $row = max(count($moneyList), count($withdrawList), count($refundList));

        $money = array_combine(array_column($moneyList, 'time'), array_column($moneyList, 'money'));
        $refundMoney = array_combine(array_column($refundList, 'time'), array_column($refundList, 'refund_money'));
        $payMoney = array_combine(array_column($withdrawList, 'time'), array_column($withdrawList, 'withdraw_money'));

        $data = [];
        $time = $endTime ? $endTime : time();
        while ($row > 0) {
            $date = date($timeFormatter, $time - ($row - 1) * $timeUnit);
            $data['time'][] = $date;
            $data['money'][] = $money[$date] ? $money[$date] : 0;
            $data['refund_money'][] = $refundMoney[$date] ? $refundMoney[$date] : 0;
            $data['withdraw_money'][] = $payMoney[$date] ? $payMoney[$date] : 0;
            $row--;
        }
        $this->success('ok', '', $data);
    }
}