<?php

namespace app\admin\controller\report;

use app\common\controller\Backend;
use fast\Date;

class User extends Backend
{
    protected $noNeedLogin = ['getData'];

    /** @var \app\common\model\User */
    public $model = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('User');
    }

    public function index()
    {
        $this->assign('cuDate', date('Y-m-d'));
        return $this->fetch();
    }

    public function getData()
    {
        $mode = $this->request->param('mode');
        $row = $this->request->param('row', 7);
        $startTime = strtotime($this->request->param('start', 0));
        $endTime = strtotime($this->request->param('end', 0));
        $endTime && $endTime += Date::DAY - 1;

        switch ($mode) {
            case 'month'://月视图
                $formatter = '%Y-%m';
                $timeUnit = Date::MONTH;
                $timeFormatter = 'Y-m';
                break;
            case 'year'://年视图
                $formatter = '%Y';
                $timeUnit = Date::YEAR;
                $timeFormatter = 'Y';
                break;
            case 'day'://日视图
            default:
                $formatter = '%Y-%m-%d';
                $timeUnit = Date::DAY;
                $timeFormatter = 'Y-m-d';
                break;
        }

        $field = "FROM_UNIXTIME(createtime,'$formatter') as time,count(id) as register";
        $row != 0 && $this->model->page(1, $row);
        $startTime && $endTime && $this->model->where(['createtime' => ['between', [$startTime, $endTime]]]);
        $registerList = $this->model->field($field)->order('time', 'desc')->group('time')->select();

        $field = "FROM_UNIXTIME(logintime,'$formatter') as time,count(id) as login";
        $row != 0 && $this->model->page(1, $row);
        $startTime && $endTime && $this->model->where(['logintime' => ['between', [$startTime, $endTime]]]);
        $loginList = $this->model->field($field)->order('time', 'desc')->group('time')->select();

        $registerList = collection($registerList)->toArray();
        $loginList = collection($loginList)->toArray();

        $row = max(count($registerList), count($loginList));

        $reg = array_combine(array_column($registerList, 'time'), array_column($registerList, 'register'));
        $log = array_combine(array_column($loginList, 'time'), array_column($loginList, 'login'));

        $data = [];
        $time = $endTime ? $endTime : time();
        while ($row > 0) {
            $date = date($timeFormatter, $time - ($row - 1) * $timeUnit);
            $data['time'][] = $date;
            $data['login'][] = $log[$date] ? $log[$date] : 0;
            $data['register'][] = $reg[$date] ? $reg[$date] : 0;
            $row--;
        }
        $this->success('ok', '', $data);
    }
}