<?php

namespace app\admin\controller\distribution;

use app\common\controller\Backend;
use app\common\library\Menu;
use think\Cache;
use think\Config;

class Setting extends Backend
{
    protected $model = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if ($this->request->isPost()) {
            $params = $this->request->request('row/a');
            $key = array_keys($params);
            $value = array_values($params);
            if (setConfig($key, $value)) {
                if (config('distribution.agent_type') != $params['agent_type']) {
                    $params['agent_type'] == '2' ? Menu::disable('distribution/apply') : Menu::enable('distribution/apply');
                    $this->success('保存成功', $this->request->url(true));
                }
                $this->success('保存成功');
            }
            $this->error('保存失败');
        }
        return $this->fetch();
    }
}